### ISSUE TITLE
Just wanted to say "thanks!"

### ISSUE THREAD

**Issue by davestewart** [psalaets/vue-jscodeshift-adapter#13]
Hey Paul,

I've been working on a new feature for one of my libs, [Alias HQ](https://github.com/davestewart/alias-hq/).

Been using JSCodeshift which is – obviously – amazing, then realised it doesn't / can't process `.vue` files.

A quick search and up your lib comes. Not only that, it's so easy to use, and the implementation is so sweet!

Just wanted to say thanks so much; you've made what could have been a show-stopper into just a super-simple commit.

I found you on Twitter, but looks like you don't post.

You ever do any freelance work on the side?

All the best,
Dave

**Comment by psalaets** [comment]
Sweet. It's nice to know that this module is still working for people.

> You ever do any freelance work on the side?

No I never got into doing freelance.
