### ISSUE TITLE
Vue template modified even if no changes were made to it

### ISSUE THREAD

**Issue by just-be-dev** [psalaets/vue-jscodeshift-adapter#3]
Based on the README I was expecting that following this convention...

```javascript
const adapt = require('vue-jscodeshift-adapter');
const someCodemod = require('some-codemod');

module.exports = adapt(someCodemod);
```

Would only result in the script block being updated. It looks like it's writing the template too, regardless of if it's needed or not. When I run my codemod (which just adjusts some js import statements) it reformats the template blocks and edits some of the attributes. 

![image](https://user-images.githubusercontent.com/3087225/37262437-81de8564-2579-11e8-9b5e-d130ed96e603.png)

I suspect that latter part is a breaking change.

**Comment by psalaets** [comment]
I published version 1.1.1 which I think fixes this.

Thanks for submitting detailed issues. I just got back from a trip and am busy trying to catch up so probably won't be looking at the others until next week.
