### ISSUE TITLE
Add an escape hatch to not process files if they're not .vue files

### ISSUE THREAD

**Issue by just-be-dev** [psalaets/vue-jscodeshift-adapter#4]
Currently if you're adapting to both js and vue files you have to handle each case in user land. I wrote a wrapper to do that, but it seems like it'd be better served to live in the library. 

It'd essentially look something like...

https://github.com/psalaets/vue-jscodeshift-adapter/blob/master/index.js#L7

```javascript
function adapt(transform) {
  return function newTransform(fileInfo, api, options) {
    if (!fileInfo.path.endsWith('.vue')) {
      return transform(fileInfo, api);
    }
  }
}
```

I suspect this will break you current tests though being as they're vue files but use the `.js` extension. We might need to write a test helper using [defineInlineTest](https://github.com/facebook/jscodeshift#defineinlinetest) to have proper vue file tests. Or we could put in a PR to jscodeshift to allow custom extensions. Maybe the former then the latter?

**Comment by psalaets** [comment]
Should be fixed in version 1.2.0
